### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by karussell** [BleachDrinker420/McOSM#1]
Is there a quick start guide on how to run or install this generator? The discord invitation is invalid unfortunately and I have not yet enough experience with minecraft :)

I just ran `sh gradlew build` and it built fine but not sure what I can do now :)

**Comment by BleachDev** [comment]
after you've done `gradlew build` the built jar should be in build/libs/ which you can use like a normal forge mod, the (quite bad) ingame usage is in the readme

**Comment by karussell** [comment]
Ok, just for my future reference:

 - download the forge mode installer from https://files.minecraftforge.net/ use the older version 1.12.2 
 - run this installer via `java -jar forge-1.12.2-14.23.5.2855-installer.jar`
 - start minecraft
 - copy the mcosm jar into .minecraft/mods/
 - restart minecraft
 
I was then able to download the osm data in the world with the /osm command and something is happening and queued. Also it says success, but I do not see anything even in a flat world and when I go to the coordinate (got them via `/osmcoords from lat lon` then `/tp <name> x ~ z`)

**Comment by karussell** [comment]
Probably my question was a bit hidden but I couldn't get it working - do you have an idea what could be wrong?

> it says success, but I do not see anything even in a flat world

Is there a step I forgot?
